### ISSUE TITLE
Fensterkontakte von Max! 

### ISSUE THREAD

**Issue by Neog8te** [ioBroker/ioBroker.maxcube#14]
Hallo zusammen, ich bin neu im smart home Bereich und habe nun auf einem raspi 2b einen iobroker voll aktualisiert laufen. Parallel dazu habe ich einen Max! Cube gekauft und 2 Fensterkontakte. Der Rest kommt erst noch.
Alles fleißig angelernt und im io eingelesen. Der cube ist da, die Kontakte auch. Leider liest er aber alles aus, außer dem Status opened oder closed. Im cube registriert er es wunderbar. 
Was mache ich falsch? Der cube ist im übrigen nicht geflasht, da ich sowas schon gelesen habe. 

Danke Neo

PS: ich muss die Kontakte zwingend mit einem Raum im EQ3 anlegen und kann diesen Wert nicht weglassen, falls dies eine Bedingung ist.

PS: Shuttekontakte mit rf 07 beginnend werden korrekt ausgelesen. Die neueren mit 09 beginnend nicht. Hat Max dort Änderungen zum auslesen getroffen?

**Comment by Rushmed** [comment]
Hallo, 
ich habe mit einem Kontakt das gleiche Problem. In meinem Haushalt sind neben Thermostaten auch sechs Fensterkontakte installiert. DAvon funktionieren fünf wie erwartet, beim Sechsten kommen in "opened" keine Werte an. 
Ähnlich der obigen Beschreibung funktionieren bei mir die Kontakte beginnend mit 1, Kontakt mit 09 jedoch nicht.
