### ISSUE TITLE
Temperatur Scanner

### ISSUE THREAD

**Issue by flinke-flasche** [ioBroker/ioBroker.maxcube#16]
Hi, 
Is it possible to implement a temperatur scanner like the !Max Scanner from FHEM?

Hallo,
ist es möglich einen Temperatur Scanner einzubauen wie beim !Max Scanner von FHEM?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Apollon77** [comment]
Detail? Links? Infos? :-)

**Comment by flinke-flasche** [comment]
https://wiki.fhem.de/wiki/MAX!_Temperatur-Scanner

**Comment by flinke-flasche** [comment]
Wäre denn so etwas möglich auch für ioBroker umzusetzen?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
