### ISSUE TITLE
Urlaubsmodus

### ISSUE THREAD

**Issue by blueTNT84** [ioBroker/ioBroker.maxcube#17]
Moin, erst Einmal danke fürs Erstellen und Teilen des Adapters.
Man kann ja den Modus Vacation wählen. Wie kann ich die Parameter (Temperatur und Endzeitpunkt) setzen?

Auf dem Handy habe ich MAX!Remote. Da kommt beim Aktivieren des Urlaubsmodus ein Dialog, in dem ich Temperatur und Enddatum/-zeit einstelle.

Wie kann ich das nun über die Vis oder Script einstellen? Denn ich finde keinen passenden Datenpunkt, der Datum und/oder Uhrzeit enthält?

MfG
Tobi

**Comment by Domi920** [comment]
Das würde mich auch sehr interessieren.
@Apollon77 hoffe es gibt eine einfache Antwort darauf.

Gruß Dominik

**Comment by Apollon77** [comment]
Kann ich euch leider nicht sagen. Müsste man mal schauen ob Google was hergibt oder FHEM Dokus was sagen.
