### ISSUE TITLE
Richtige Version 0.1.2 oder 1.0.1?

### ISSUE THREAD

**Issue by RK62** [ioBroker/ioBroker.maxcube#19]
Welche Version ist hier richtig?
npm zeigt noch die 0.1.2, das Changelog ist schon bei 1.0.1

Bei einem iorbroker-Restore hat das bei mir Probleme aufgeworfen, weil die 1.0.1 da nicht installieren werden konnte.

Oder doch direkt con Github installieren?

Danke, Ralf

**Comment by Apollon77** [comment]
Ich glaube einfach das es nach der 0.1.2 und den Erweiterungen der 1.0.0 bzw 1.0.1 nie wirkoiches User Feedback gab. Daher können die Entwickler die solche Geräte nicht wirklich haben nicht sagen ob Ihr Version ok ist oder nicht.

Wenn Du jetzt die Rückmeldung gibst das die 1.0.1 ok ist ... dann kann man die auch mal eröffentlichen

**Comment by RK62** [comment]
Ups! Läuft seit Jahren einwandfrei bei mir mit Thermostaten, Wandthermostaten und Fensterkontakten. Ist scheinbar auch bei einigen anderen Usern seit 12/2018 im Einsatz, siehe  https://forum.iobroker.net/topic/6396/adapter-max-cube/151.

→ Kann also veröffentlicht werden.

**Comment by blueTNT84** [comment]
Moin, ich nutze die 1.0.1 auch schon seit Monaten.
(aktuell:
NPM 6.14.4
Node.js v12.16.2
js-controller 3.1.6)

**Comment by RK62** [comment]
Zur Info: 
Das MAX! System wird eingestellt, momentan gibt es ein Wechselangebot zu _homematic IP_:
https://de.elv.com/teilnahmebedingungen-max-wechselangebot

**Comment by Apollon77** [comment]
Ok, ich habe mal aktualiser, versucht mal die 1.0.2 hier vom GitHub ... wenn die auch tut dann bringen wir die bis stable

**Comment by blueTNT84** [comment]
Gestern habe ich auf Version 1.0.2 aktualisiert. Bisher konnte ich keine Fehler feststellen.
Ich habe erfolgreich
- den Modus zwischen Boost, Manu und Auto gewechselt
- Temperaturen verstellt
- Temperaturen anzeigen lassen
- Fenster geöffnet

Gibt es sonst noch was, was ich loggen oder testen sollte?

**Comment by Apollon77** [comment]
1.0.2 geht ins latest ...

**Comment by Apollon77** [comment]
Feedback zur 1.0.2?

**Comment by RK62** [comment]
Ich habe das Wechselangebot genutzt und kann den Adapter daher nicht mehr testen.
