### ISSUE TITLE
Ungewollte Modusänderung auf Manuell bei Temperaturänderung 

### ISSUE THREAD

**Issue by Domi920** [ioBroker/ioBroker.maxcube#23]
Hallo,
mir ist aufgefallen, dass bei einer Soll-Temperatur Änderung eines Heizkörperthermostats über die Objektliste (oder auch VIS) der Modus des Thermostats von Automatik immer auf Manuell geschalten wird.

Somit kann man keine temporäre Änderung vornehmen.
Das finde ich unpraktisch.

Gibt es eine Möglichkeit diese ungewollte Modusänderung zu unterbinden?

Gruß Dominik

**Comment by blueTNT84** [comment]
Ich weiß nicht, ob man es verhindern kann, aber ich habe ich einem Forum mal ein Script gefunden, welches wieder zurück aus AUTO stellt:

/**
 * ioBroker Skript zum automatischen Zurücksetzen des Modus von MAX! Thermostaten
 * auf Auto, wenn die Solltemperatur im Auto-Modus geändert wurde.
 *
 * Dies ist erforderlich, da die Thermostate durch den Max! Cube Adapter bei einer
 * manuellen Änderung der Solltemperatur immer in den manuellen Modus versetzt werden.
 * Dieses Script erkennt diese Änderung und setzt den Modus zurück auf Auto.
 *
 * Copyright (c) 2019 Peter Müller <peter@crycode.de> (https://crycode.de)
 *
 * https://crycode.de/homepi-iobroker-max-heizungssteuerung#comment-16068
 */

/**
 * Liste an Thermostaten, die ignoriert werden sollen.
 * Dies können z.B. Wandthermostate sein, da diese zusammen mit dem zugehörigen 
 * Heizkörperthermostat arbeiten.
 */
const thermostatIgnore = [
    'thermostat_18abcd'
];

// Auflistung aller Thermostate holen
const devices = $('maxcube.0.devices.thermostat_*.mode');

// Alle Thermostate durchgehen
devices.each((id) => {
    id = id.replace(/\.mode$/, '');

    // Prüfen ob das aktuelle Thermostat ignoriert werden soll
    const rfId = id.split('.')[3];
    if (thermostatIgnore.indexOf(rfId) !== -1) return;

    log(`setup mode switch back for ${id}`);

    // Handler für einen Moduswechsel anlegen
    on({id: `${id}.mode`, change: 'ne'}, (obj) => {
        // AUTO(0) -> MANUAL(1) ?
        if (obj.newState.val === 1 && obj.oldState.val === 0) {
            // Letzte Sollwertänderung laden und Zeitpunkt prüfen
            getState(`${id}.setpoint`, (err, state) => {
                // Wechsel des Modus innerhalb von 10 Sekunden nach dem Wechsel des Sollwerts?
                if (state.ts > obj.newState.ts - 10000) {
                    // Modus zurück auf Auto setzen
                    log(`switching ${id} back to auto mode`);
                    setState(`${id}.mode`, 0);
                }
            });
        }
    });
});

**Comment by Domi920** [comment]
@blueTNT84 Danke für deinen Beitrag.
Funktioniert einwandfrei!

@Apollon77 ist dieser "automatische" Moduswechsel beabsichtigt im Programmiercode hinterlegt?
Falls ja, könnte man evtl. einen Einstellungshaken in den Instanz-Einstellungen hinzufügen oder?

**Comment by Apollon77** [comment]
Ehrlich, keine Ahnung. Ich habe den Adapter nicht geschrieben sondern nur Versuch bei einigen bugs auszuhelfen.

**Comment by Domi920** [comment]
Vielen Dank an alle! :-) 
Gruß Dominik

**Comment by Apollon77** [comment]
Lss doch offen wenn das Problem besteht
