### ISSUE TITLE
Payload abschalten?

### ISSUE THREAD

**Issue by charly9898** [ioBroker/ioBroker.maxcube#4]
Gibt es eine Möglichkeit im Log die payload abzuschalten?
Die Logdatei wird dadurch stark vergrößert

**Comment by Apollon77** [comment]
Beispiel aus de log?

**Comment by charly9898** [comment]
![max](https://user-images.githubusercontent.com/38829413/39966973-7998300a-56b4-11e8-8c88-4f5f587e2300.JPG)

**Comment by GermanBluefox** [comment]
I think It must be debug level.

**Comment by charly9898** [comment]
Should user data only appear in the events?
In my opinion, only connection data or similar should be written in the log file.
It takes a lot of effort to find important clues.
The payload is only written by maxcube. Other adapters work without problems.
Filtering is also not possible, since the display is always displayed except in error mode.

**Comment by Apollon77** [comment]
As soon as I find time I will change the log level. For now you can simply higher the loglevel to "warn" instead of "info" and the messges also would disapear

**Comment by Apollon77** [comment]
No it just mioves to debug loglevel and if someone needs to see it he can switch the loglevel.

**Comment by charly9898** [comment]
With the exception of the warnlevel and errorlevel, the payload always appears. 
Other adapters do not write a payload. There I find everything in the events tab. 
I would be fine this function could be turned off optionally

**Comment by Apollon77** [comment]
Please do not always close the issue if it is not fixed!

**Comment by GermanBluefox** [comment]
Done

**Comment by charly9898** [comment]
I'm sorry. Version 1.0.0 does not work.
This error is output in the log file:

![fehler 1 0 0](https://user-images.githubusercontent.com/38829413/40575622-97b52c3a-60e8-11e8-8497-8b691b12e535.JPG)

**Comment by GermanBluefox** [comment]
Please retry from github

**Comment by charly9898** [comment]
Thanks!!
It works

![fehler 1 0 0](https://user-images.githubusercontent.com/38829413/40579343-afdbbfda-6125-11e8-9317-954508f9952d.JPG)
