### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by useful-idiot** [ioBroker/ioBroker.maxcube#6]
Hi this is not an issue, just a "feature request" - no, not even this. Just a question, if it is possible to add a choice to make a (non) exclusive connection to the cube, so other software may also access it (in openhab the author simply added a var and closes the connection if true after sending the commands)

Further, is there any possibility to set the temperature to "Eco" (like in e.g. FHEM?) and back?

Please advice me if this is the wrong place for requests, thanks in advance!

**Comment by DanielWeeber** [comment]
> Hi this is not an issue, just a "feature request" - no, not even this. Just a question, if it is possible to add a choice to make a (non) exclusive connection to the cube, so other software may also access it (in openhab the author simply added a var and closes the connection if true after sending the commands)
> 

But there will be no more feedback again.

> Further, is there any possibility to set the temperature to "Eco" (like in e.g. FHEM?) and back?

Currently not. ECO is only available for the complete home, the thermostat itself only has AUTO, MANUAL, VACATION and BOOST if I remember correctly.
