### ISSUE TITLE
Adapter ist oft nicht mit Maxcube verbunden

### ISSUE THREAD

**Issue by Mazdaracer121** [ioBroker/ioBroker.maxcube#8]
Der Adapter verbindet sich oft nicht mit dem Maxcube.

e
![38761794_1885702854825545_241477930557898752_n](https://user-images.githubusercontent.com/42050266/44120290-37ea28dc-a01c-11e8-969a-b1c0bfd044c4.jpg)
rror | by controller[0]: { Error: connect ETIMEDOUT 192.168.178.108:62910
-- | --

**Comment by Apollon77** [comment]
Can it be that when that happens you are connected with the app in parallel? The cube only supports one connection at a time ...
